server:
  port: 8087

spring:
  application:
    name: dashboard-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka:eureka123@localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Feign configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic

logging:
  level:
    com.ecommerce.dashboardservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics